version: "3.7"

services:
  tor:
    image: dperson/torproxy
    container_name: wordpress-tor
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/tor:/etc/tor
      - wordpress_tor_data:/var/lib/tor
    networks:
      - default
    command: -f /etc/tor/torrc

volumes:
  wordpress_tor_data:

networks:
  default:
    external: true
    name: umbrel_main_network
